// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AgreeRequestsMessage struct {
	ChId                 string   `protobuf:"bytes,1,opt,name=ch_id,json=chId,proto3" json:"ch_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Pn                   string   `protobuf:"bytes,3,opt,name=pn,proto3" json:"pn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgreeRequestsMessage) Reset()         { *m = AgreeRequestsMessage{} }
func (m *AgreeRequestsMessage) String() string { return proto.CompactTextString(m) }
func (*AgreeRequestsMessage) ProtoMessage()    {}
func (*AgreeRequestsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{0}
}

func (m *AgreeRequestsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgreeRequestsMessage.Unmarshal(m, b)
}
func (m *AgreeRequestsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgreeRequestsMessage.Marshal(b, m, deterministic)
}
func (m *AgreeRequestsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgreeRequestsMessage.Merge(m, src)
}
func (m *AgreeRequestsMessage) XXX_Size() int {
	return xxx_messageInfo_AgreeRequestsMessage.Size(m)
}
func (m *AgreeRequestsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AgreeRequestsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AgreeRequestsMessage proto.InternalMessageInfo

func (m *AgreeRequestsMessage) GetChId() string {
	if m != nil {
		return m.ChId
	}
	return ""
}

func (m *AgreeRequestsMessage) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AgreeRequestsMessage) GetPn() string {
	if m != nil {
		return m.Pn
	}
	return ""
}

type UpdateRequestsMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequestsMessage) Reset()         { *m = UpdateRequestsMessage{} }
func (m *UpdateRequestsMessage) String() string { return proto.CompactTextString(m) }
func (*UpdateRequestsMessage) ProtoMessage()    {}
func (*UpdateRequestsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{1}
}

func (m *UpdateRequestsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequestsMessage.Unmarshal(m, b)
}
func (m *UpdateRequestsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequestsMessage.Marshal(b, m, deterministic)
}
func (m *UpdateRequestsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequestsMessage.Merge(m, src)
}
func (m *UpdateRequestsMessage) XXX_Size() int {
	return xxx_messageInfo_UpdateRequestsMessage.Size(m)
}
func (m *UpdateRequestsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequestsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequestsMessage proto.InternalMessageInfo

type ConfirmRequestsMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmRequestsMessage) Reset()         { *m = ConfirmRequestsMessage{} }
func (m *ConfirmRequestsMessage) String() string { return proto.CompactTextString(m) }
func (*ConfirmRequestsMessage) ProtoMessage()    {}
func (*ConfirmRequestsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{2}
}

func (m *ConfirmRequestsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmRequestsMessage.Unmarshal(m, b)
}
func (m *ConfirmRequestsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmRequestsMessage.Marshal(b, m, deterministic)
}
func (m *ConfirmRequestsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmRequestsMessage.Merge(m, src)
}
func (m *ConfirmRequestsMessage) XXX_Size() int {
	return xxx_messageInfo_ConfirmRequestsMessage.Size(m)
}
func (m *ConfirmRequestsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmRequestsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmRequestsMessage proto.InternalMessageInfo

type ChannelIDs struct {
	ChIds                []*ChannelIDs_ChannelID `protobuf:"bytes,1,rep,name=ch_ids,json=chIds,proto3" json:"ch_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ChannelIDs) Reset()         { *m = ChannelIDs{} }
func (m *ChannelIDs) String() string { return proto.CompactTextString(m) }
func (*ChannelIDs) ProtoMessage()    {}
func (*ChannelIDs) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{3}
}

func (m *ChannelIDs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelIDs.Unmarshal(m, b)
}
func (m *ChannelIDs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelIDs.Marshal(b, m, deterministic)
}
func (m *ChannelIDs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelIDs.Merge(m, src)
}
func (m *ChannelIDs) XXX_Size() int {
	return xxx_messageInfo_ChannelIDs.Size(m)
}
func (m *ChannelIDs) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelIDs.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelIDs proto.InternalMessageInfo

func (m *ChannelIDs) GetChIds() []*ChannelIDs_ChannelID {
	if m != nil {
		return m.ChIds
	}
	return nil
}

type ChannelIDs_ChannelID struct {
	ChId                 string   `protobuf:"bytes,1,opt,name=ch_id,json=chId,proto3" json:"ch_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelIDs_ChannelID) Reset()         { *m = ChannelIDs_ChannelID{} }
func (m *ChannelIDs_ChannelID) String() string { return proto.CompactTextString(m) }
func (*ChannelIDs_ChannelID) ProtoMessage()    {}
func (*ChannelIDs_ChannelID) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{3, 0}
}

func (m *ChannelIDs_ChannelID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelIDs_ChannelID.Unmarshal(m, b)
}
func (m *ChannelIDs_ChannelID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelIDs_ChannelID.Marshal(b, m, deterministic)
}
func (m *ChannelIDs_ChannelID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelIDs_ChannelID.Merge(m, src)
}
func (m *ChannelIDs_ChannelID) XXX_Size() int {
	return xxx_messageInfo_ChannelIDs_ChannelID.Size(m)
}
func (m *ChannelIDs_ChannelID) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelIDs_ChannelID.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelIDs_ChannelID proto.InternalMessageInfo

func (m *ChannelIDs_ChannelID) GetChId() string {
	if m != nil {
		return m.ChId
	}
	return ""
}

type Payments struct {
	Pd                   []*Payments_PaymentData `protobuf:"bytes,1,rep,name=pd,proto3" json:"pd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Payments) Reset()         { *m = Payments{} }
func (m *Payments) String() string { return proto.CompactTextString(m) }
func (*Payments) ProtoMessage()    {}
func (*Payments) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{4}
}

func (m *Payments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payments.Unmarshal(m, b)
}
func (m *Payments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payments.Marshal(b, m, deterministic)
}
func (m *Payments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payments.Merge(m, src)
}
func (m *Payments) XXX_Size() int {
	return xxx_messageInfo_Payments.Size(m)
}
func (m *Payments) XXX_DiscardUnknown() {
	xxx_messageInfo_Payments.DiscardUnknown(m)
}

var xxx_messageInfo_Payments proto.InternalMessageInfo

func (m *Payments) GetPd() []*Payments_PaymentData {
	if m != nil {
		return m.Pd
	}
	return nil
}

type Payments_PaymentData struct {
	ChId                 string   `protobuf:"bytes,1,opt,name=ch_id,json=chId,proto3" json:"ch_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Pay                  bool     `protobuf:"varint,3,opt,name=pay,proto3" json:"pay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payments_PaymentData) Reset()         { *m = Payments_PaymentData{} }
func (m *Payments_PaymentData) String() string { return proto.CompactTextString(m) }
func (*Payments_PaymentData) ProtoMessage()    {}
func (*Payments_PaymentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{4, 0}
}

func (m *Payments_PaymentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payments_PaymentData.Unmarshal(m, b)
}
func (m *Payments_PaymentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payments_PaymentData.Marshal(b, m, deterministic)
}
func (m *Payments_PaymentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payments_PaymentData.Merge(m, src)
}
func (m *Payments_PaymentData) XXX_Size() int {
	return xxx_messageInfo_Payments_PaymentData.Size(m)
}
func (m *Payments_PaymentData) XXX_DiscardUnknown() {
	xxx_messageInfo_Payments_PaymentData.DiscardUnknown(m)
}

var xxx_messageInfo_Payments_PaymentData proto.InternalMessageInfo

func (m *Payments_PaymentData) GetChId() string {
	if m != nil {
		return m.ChId
	}
	return ""
}

func (m *Payments_PaymentData) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Payments_PaymentData) GetPay() bool {
	if m != nil {
		return m.Pay
	}
	return false
}

type Result struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{5}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*AgreeRequestsMessage)(nil), "AgreeRequestsMessage")
	proto.RegisterType((*UpdateRequestsMessage)(nil), "UpdateRequestsMessage")
	proto.RegisterType((*ConfirmRequestsMessage)(nil), "ConfirmRequestsMessage")
	proto.RegisterType((*ChannelIDs)(nil), "ChannelIDs")
	proto.RegisterType((*ChannelIDs_ChannelID)(nil), "ChannelIDs.ChannelID")
	proto.RegisterType((*Payments)(nil), "Payments")
	proto.RegisterType((*Payments_PaymentData)(nil), "Payments.PaymentData")
	proto.RegisterType((*Result)(nil), "Result")
}

func init() { proto.RegisterFile("client.proto", fileDescriptor_014de31d7ac8c57c) }

var fileDescriptor_014de31d7ac8c57c = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x41, 0x4f, 0xb3, 0x40,
	0x10, 0xfd, 0xd8, 0x7e, 0xc5, 0x76, 0xaa, 0x4d, 0xb3, 0x4a, 0x25, 0x9c, 0xc8, 0x26, 0x2a, 0x07,
	0xc3, 0xa1, 0xfa, 0x07, 0x0c, 0xbd, 0x34, 0xd1, 0xc4, 0xac, 0xf1, 0x66, 0x62, 0x56, 0x58, 0x0b,
	0x09, 0x2c, 0x2b, 0xbb, 0x1c, 0x7a, 0xf2, 0x27, 0xf8, 0x97, 0x0d, 0x5b, 0x4a, 0x49, 0xd3, 0x8b,
	0xb7, 0x37, 0x33, 0x8f, 0x37, 0xc3, 0x7b, 0x0b, 0xa7, 0x71, 0x9e, 0x71, 0xa1, 0x43, 0x59, 0x95,
	0xba, 0x24, 0x2f, 0x70, 0xf1, 0xb0, 0xae, 0x38, 0xa7, 0xfc, 0xab, 0xe6, 0x4a, 0xab, 0x27, 0xae,
	0x14, 0x5b, 0x73, 0x7c, 0x0e, 0xc3, 0x38, 0x7d, 0xcf, 0x12, 0xd7, 0xf2, 0xad, 0x60, 0x4c, 0xff,
	0xc7, 0xe9, 0x2a, 0xc1, 0x73, 0xb0, 0x59, 0x51, 0xd6, 0x42, 0xbb, 0xc8, 0xb7, 0x02, 0x44, 0xdb,
	0x0a, 0x4f, 0x01, 0x49, 0xe1, 0x0e, 0x0c, 0x13, 0x49, 0x41, 0x2e, 0xc1, 0x79, 0x95, 0x09, 0xd3,
	0x87, 0xaa, 0xc4, 0x85, 0x79, 0x54, 0x8a, 0xcf, 0xac, 0x2a, 0x0e, 0x27, 0x6f, 0x00, 0x51, 0xca,
	0x84, 0xe0, 0xf9, 0x6a, 0xa9, 0xf0, 0x2d, 0xd8, 0x66, 0xbb, 0x72, 0x2d, 0x7f, 0x10, 0x4c, 0x16,
	0x4e, 0xb8, 0x1f, 0xee, 0x21, 0x1d, 0x36, 0x57, 0x29, 0xcf, 0x87, 0x71, 0xd7, 0x3b, 0x7a, 0x38,
	0xf9, 0x86, 0xd1, 0x33, 0xdb, 0x14, 0x5c, 0x68, 0x85, 0xaf, 0x00, 0xc9, 0xa4, 0xd3, 0xdd, 0xb5,
	0x77, 0x60, 0xc9, 0x34, 0xa3, 0x48, 0x26, 0xde, 0x23, 0x4c, 0x7a, 0xad, 0xbf, 0xf9, 0x31, 0x83,
	0x81, 0x64, 0x1b, 0x63, 0xc8, 0x88, 0x36, 0x90, 0xf8, 0x60, 0x53, 0xae, 0xea, 0x5c, 0x37, 0xdf,
	0x54, 0x06, 0xb5, 0x4a, 0x6d, 0xb5, 0xf8, 0xb1, 0xc0, 0x8e, 0x4c, 0x32, 0xf8, 0x1e, 0x66, 0xac,
	0xc9, 0xa4, 0x59, 0xde, 0xfa, 0x84, 0x9d, 0xf0, 0x58, 0x4c, 0xde, 0x49, 0xb8, 0x95, 0x25, 0xff,
	0xf0, 0x0d, 0x9c, 0xd5, 0x7d, 0xd3, 0xf1, 0xa4, 0x67, 0x5a, 0x9f, 0x78, 0x0d, 0xd3, 0x78, 0x1b,
	0x42, 0xfb, 0x83, 0x78, 0xdc, 0xd9, 0xd0, 0xe3, 0x7d, 0xd8, 0xe6, 0x85, 0xdc, 0xfd, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x18, 0x53, 0xb9, 0x62, 0x31, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClientClient is the client API for Client service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientClient interface {
	AgreementRequest(ctx context.Context, in *AgreeRequestsMessage, opts ...grpc.CallOption) (*Result, error)
	UpdateRequest(ctx context.Context, in *ChannelIDs, opts ...grpc.CallOption) (*Result, error)
	ConfirmPayment(ctx context.Context, in *Payments, opts ...grpc.CallOption) (*Result, error)
}

type clientClient struct {
	cc *grpc.ClientConn
}

func NewClientClient(cc *grpc.ClientConn) ClientClient {
	return &clientClient{cc}
}

func (c *clientClient) AgreementRequest(ctx context.Context, in *AgreeRequestsMessage, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/Client/agreementRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) UpdateRequest(ctx context.Context, in *ChannelIDs, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/Client/updateRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) ConfirmPayment(ctx context.Context, in *Payments, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/Client/confirmPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServer is the server API for Client service.
type ClientServer interface {
	AgreementRequest(context.Context, *AgreeRequestsMessage) (*Result, error)
	UpdateRequest(context.Context, *ChannelIDs) (*Result, error)
	ConfirmPayment(context.Context, *Payments) (*Result, error)
}

// UnimplementedClientServer can be embedded to have forward compatible implementations.
type UnimplementedClientServer struct {
}

func (*UnimplementedClientServer) AgreementRequest(ctx context.Context, req *AgreeRequestsMessage) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgreementRequest not implemented")
}
func (*UnimplementedClientServer) UpdateRequest(ctx context.Context, req *ChannelIDs) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRequest not implemented")
}
func (*UnimplementedClientServer) ConfirmPayment(ctx context.Context, req *Payments) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmPayment not implemented")
}

func RegisterClientServer(s *grpc.Server, srv ClientServer) {
	s.RegisterService(&_Client_serviceDesc, srv)
}

func _Client_AgreementRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgreeRequestsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).AgreementRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Client/AgreementRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).AgreementRequest(ctx, req.(*AgreeRequestsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_UpdateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelIDs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).UpdateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Client/UpdateRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).UpdateRequest(ctx, req.(*ChannelIDs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_ConfirmPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Payments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).ConfirmPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Client/ConfirmPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).ConfirmPayment(ctx, req.(*Payments))
	}
	return interceptor(ctx, in, info, handler)
}

var _Client_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Client",
	HandlerType: (*ClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "agreementRequest",
			Handler:    _Client_AgreementRequest_Handler,
		},
		{
			MethodName: "updateRequest",
			Handler:    _Client_UpdateRequest_Handler,
		},
		{
			MethodName: "confirmPayment",
			Handler:    _Client_ConfirmPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client.proto",
}
